/* Presentation reads the generated design; materials and cameras never edit it. */
(function(root){'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const palettes={clay:{label:'Warm clay'},sage:{label:'Sage stone'},charcoal:{label:'Soft charcoal'},white:{label:'White study model'}};
const prefs={camera:'axon',material:'clay',light:'overcast',context:true,trees:true,proposal:true};let active=null,exportShot=null;
const rect=r=>[[r.x,r.y],[r.x+r.w,r.y],[r.x+r.w,r.y+r.h],[r.x,r.y+r.h]];
function revision(r){let h=2166136261;const s=JSON.stringify([r.o,r.levels.map(l=>[l.g.built,l.g.cores,l.g.corridors,l.units,l.rooms])]);for(let i=0;i<s.length;i++)h=Math.imul(h^s.charCodeAt(i),16777619);return (h>>>0).toString(16).padStart(8,'0').toUpperCase();}
function cameraPose(r,kind){if(kind==='axon')kind='corner';const o=r.o,c=[o.W/2,o.D/2],height=o.commercial?o.groundFtf+(o.floors-1)*o.ftf:o.floors*o.ftf,side=o.streetSide||o.articulationFront||'top',front={top:[0,-1],bottom:[0,1],left:[-1,0],right:[1,0]}[side],n=kind==='lane'?front.map(v=>-v):front,span=Math.max(o.W,o.D,height),lot=r.context?.sitePoly||rect({x:0,y:0,w:o.W,h:o.D}),edge=Math.max(...lot.map(p=>(p[0]-c[0])*n[0]+(p[1]-c[1])*n[1])),d=kind==='corner'?span*1.6:edge+(kind==='lane'?3:8),offset=kind==='corner'?.6:kind==='hero'?.65:0;
 return {position:[c[0]+(n[0]+n[1]*offset)*d,kind==='corner'?height+span*.65:1.7,c[1]+(n[1]-n[0]*offset)*d],target:[c[0],kind==='corner'?height*.35:height*.4,c[1]]};}
// Fit the proposal in the available viewport without placing street cameras
// inside the opposite row of buildings. Tight streets need a wider lens.
function fitLens(camera,r){camera.updateMatrixWorld();if(camera.isOrthographicCamera){const height=r.o.commercial?r.o.groundFtf+(r.o.floors-1)*r.o.ftf:r.o.floors*r.o.ftf;let extent=0;for(const x of [0,r.o.W])for(const y of [0,r.o.D])for(const z of [0,height]){const p=new root.THREE.Vector3(x,z,-y).applyMatrix4(camera.matrixWorldInverse);extent=Math.max(extent,Math.abs(p.y),Math.abs(p.x)/camera.aspect);}extent*=1.55;camera.left=-extent*camera.aspect;camera.right=extent*camera.aspect;camera.top=extent;camera.bottom=-extent;camera.updateProjectionMatrix();return;}const height=r.o.commercial?r.o.groundFtf+(r.o.floors-1)*r.o.ftf:r.o.floors*r.o.ftf;let tangent=0;
 for(const x of [0,r.o.W])for(const y of [0,r.o.D])for(const z of [0,height]){const p=new root.THREE.Vector3(x,z,-y).applyMatrix4(camera.matrixWorldInverse);if(p.z<-.1)tangent=Math.max(tangent,Math.abs(p.y/-p.z),Math.abs(p.x/-p.z)/camera.aspect);}
 camera.fov=Math.max(35,Math.min(110,2*Math.atan(tangent*1.1)*180/Math.PI));camera.updateProjectionMatrix();}
function sceneModel(r,around,settings=prefs){
 // Drawn after the reference axonometrics: a white context in fine ink, the ground in textures at their real size,
 // and the proposal the only object with a material. PRESENTATION_DRAWING holds the drawing language.
 const T=root.THREE,D=root.PRESENTATION_DETAIL,X=root.PRESENTATION_DRAWING,group=new T.Group(),proposal=new T.Group(),context=new T.Group(),trees=new T.Group();group.add(context,trees,proposal);
 const S=X.surfaces(),C=X.cladding(palettes[settings.material]?settings.material:'clay'),wall=C.wall,frame=C.frame,glass=C.glass,rail=new T.MeshLambertMaterial({color:0x3b4146}),doorMat=rail,stone=C.coping;
 const V=p=>new T.Vector3(p[0],p[2],-p[1]),prism=(poly,z,h,mat,parent,tag)=>X.prism(poly,z,h,mat,parent,tag),box=(q,z,h,mat,parent=proposal,tag)=>X.box(q,z,h,mat,parent,tag);
 function line(a,b,mat,radius=.035,parent=proposal){const start=V(a),end=V(b),direction=end.clone().sub(start),mesh=new T.Mesh(new T.CylinderGeometry(radius,radius,direction.length(),6),mat);mesh.position.copy(start.clone().add(end).multiplyScalar(.5));mesh.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),direction.normalize());parent.add(mesh);}
 const lot=r.context?.sitePoly||rect({x:0,y:0,w:r.o.W,h:r.o.D}),band=around?.band||{x0:-30,y0:-30,x1:r.o.W+30,y1:r.o.D+30};
 box({x:band.x0,y:band.y0,w:band.x1-band.x0,h:band.y1-band.y0},-.18,.12,S.asphalt,context,'asphalt');
 for(const p of around?.parcels||[])prism(p.poly,-.04,.05,/^(R1|R3|RT|RS)/.test(p.zone||'')?S.lawn:S.paving,context,'parcel');
 prism(lot,0,.08,S.lawnSite,group,'site');X.propertyLine(lot,context);
 D.neighbours(around,context,{wall:S.contextWall,roof:S.contextRoof,flat:S.contextFlat});D.contextLinework(context,S.contextInk);X.fatten(context,'context-outline',X.STYLE.context);
 const entrance=(r.levels[0]?.rooms||[]).find(q=>q.on!==false&&q.entryPoint)?.entryPoint;
 const zOf=l=>r.o.commercial?(l.level===1?0:r.o.groundFtf+(l.level-2)*r.o.ftf):(l.level-1)*r.o.ftf,hOf=l=>r.o.commercial&&l.level===1?r.o.groundFtf:r.o.ftf;
 let openingCount=0;
 for(const l of r.levels){const z=zOf(l),h=hOf(l),open=l.g.corridors.concat(l.g.cores).filter(q=>q.exterior);let solid=l.g.built;
  for(const q of open)solid=solid.flatMap(p=>root.FLOOR_DESIGN.subtract(p,q));
  if(l.parking){for(const q of solid)box(q,z,.25,stone);for(const q of l.parking.columns||[])box(q,z,h,wall);for(const q of l.g.cores)box(q,z,h,wall);for(const q of (l.rooms||[]).filter(p=>p.on!==false&&p.name!=='Flexible space'))box(q,z,h,wall);}
  else D.shell(solid,l,z,h,l.level===1&&settings.material!=='white'?C.plinth:wall,proposal,l.level===1?entrance:null,null);
  for(const q of open)box(q,z,.25,stone);
  // Doors onto an exterior gallery are visible from outside: every unit entry and every stair and lift door on an open run.
  if(open.length){const CL=root.CORE_LAYOUT,pts=l.units.filter(u=>u.door).map(u=>({p:u.door,w:.9})).concat(l.g.cores.flatMap(c=>{const t=CL?.contacts(c,l.g.corridors)[0];return t?(CL.cars?.(c,t.side)>1?CL.openings(c,t.side).map(o=>({p:o.point,w:1.1})):[{p:t.point,w:c.kind==='elevator'?1.1:1.2}]):[];}));
   for(const {p,w} of pts){const q=open.find(q=>p[0]>=q.x-.05&&p[0]<=q.x+q.w+.05&&p[1]>=q.y-.05&&p[1]<=q.y+q.h+.05);if(!q)continue;const vertical=Math.abs(p[0]-q.x)<.05||Math.abs(p[0]-q.x-q.w)<.05;
    box(vertical?{x:p[0]-.04,y:p[1]-w/2,w:.08,h:w}:{x:p[0]-w/2,y:p[1]-.04,w,h:.08},z+.25,2.1,doorMat);}}
  // gallery guards: a top rail and fine pickets, drawn dark so they read as linework
  for(const e of root.CORRIDOR_NETWORK.exposedEdges(open,l.g,l.o)){const horizontal=['top','bottom'].includes(e.side),pt=(a,up)=>horizontal?[a,e.v,up]:[e.v,a,up];line(pt(e.a,z+1.32),pt(e.z,z+1.32),rail,.03);const n=Math.ceil((e.z-e.a)/.12);for(let i=0;i<=n;i++){const a=e.a+(e.z-e.a)*i/n;line(pt(a,z+.25),pt(a,z+1.32),rail,.01);}}
  for(const w of root.EXPLORE_DRAW.windows(l)){const horizontal=['top','bottom'].includes(w.side),sign=['top','left'].includes(w.side)?-1:1,at=w.v-sign*.16,pt=(a,up)=>horizontal?[a,at,up]:[at,a,up],a=z+w.sill,b=Math.min(z+h-.25,a+w.height);if(b<=a)continue;
   const points=[pt(w.a,a),pt(w.z,a),pt(w.z,b),pt(w.a,b)],geo=new T.BufferGeometry().setFromPoints(points.map(V));geo.setIndex([0,1,2,0,2,3]);geo.computeVertexNormals();const mesh=new T.Mesh(geo,glass);mesh.userData.windowId=w.id;proposal.add(mesh);openingCount++;
   const sill=horizontal?{x:w.a-.06,y:w.v-.09,w:w.z-w.a+.12,h:.18}:{x:w.v-.09,y:w.a-.06,w:.18,h:w.z-w.a+.12};box(sill,a-.055,.055,stone);
   // light frames set in the reveal; a mullion only where the opening is wider than a single sash
   for(let i=0;i<4;i++)line(points[i],points[(i+1)%4],frame,.025);if(w.z-w.a>1.4)line(pt((w.a+w.z)/2,a),pt((w.a+w.z)/2,b),frame,.025);
  }
 }
 // The actual lobby entrance is the focal point at street level: a glazed door under a canopy.
 if(entrance){const s=entrance.side,horizontal=['top','bottom'].includes(s),sg=['top','left'].includes(s)?-1:1,q=horizontal?{x:entrance.x-.65,y:entrance.y+sg*.04-.035,w:1.3,h:.07}:{x:entrance.x+sg*.04-.035,y:entrance.y-.65,w:.07,h:1.3};box(q,.08,2.35,glass);}
 const roofParts=X.roofs(r,r.levels,{wall,coping:C.coping,gravel:C.roof,terrace:S.terrace},proposal,zOf,hOf),added=roofParts.concat(X.canopy(entrance,{coping:C.coping},proposal));added.rails=roofParts.rails;added.parapetOuter=roofParts.parapetOuter;added.parapetInner=roofParts.parapetInner;
 group.updateMatrixWorld(true);
 proposal.add(X.proposalLines(r,r.levels,zOf,hOf,added,S));
 // Street section, trees, people, cars and street lights: illustrative, placed from the site's street edges.
 X.streetscape(r,entrance,S,context,trees,[]);
 proposal.visible=settings.proposal;context.visible=settings.context;trees.visible=settings.context&&settings.trees;
 return {group,proposal,context,trees,openingCount};
}
function dispose(){if(!active)return;cancelAnimationFrame(active.raf);active.ro?.disconnect();active.controls?.dispose();active.scene.traverse(q=>{q.geometry?.dispose();for(const m of q.material?(Array.isArray(q.material)?q.material:[q.material]):[]){m.map?.dispose();if(m.bumpMap!==m.map)m.bumpMap?.dispose();m.dispose();}});active.environment?.dispose();active.renderer.dispose();active=null;}
function render({stage,result:r,context:ctx,frame,states,extra}){
 dispose();const SH=root.WORKSPACE_SHELL,ready=r.ok&&r.count>0,around=frame&&root.SITE_CONTEXT?.near(frame,frame.local,{radius:45,offset:[ctx.bounds.x,ctx.bounds.y]});
 stage.innerHTML=`<section class="ex-view pr-view" data-view="presentation"><div class="pr-heading"><div><h1>Building in context</h1><p>${esc(ctx.addr)} · ${ready?esc(designName()):'not ready'}</p></div><span class="pr-camera">Elevated corner</span></div><div class="pr-canvas" role="img" aria-label="Interactive building and neighbourhood rendering" tabindex="0"></div><div class="pr-caption" aria-live="polite">${around?.buildings?.length?'Vancouver parcel geometry · estimated neighbouring buildings · illustrative planting and finishes.':'Neighbourhood data unavailable. Showing the proposal and site only.'}</div></section>`;
 const panel=stage.firstElementChild,host=panel.querySelector('.pr-canvas');
 const mode=`<section><h3>Presentation</h3><p>Explore the current design in its surroundings.</p><div class="pr-cameras" role="group" aria-label="Camera views">${[['axon','Neighbourhood axon'],['hero','Street corner'],['street','Street view'],['corner','Elevated corner'],['lane','Lane view']].map(([k,t])=>`<button data-pr-camera="${k}" aria-pressed="${prefs.camera===k}">${t}</button>`).join('')}</div></section><section><h3>Appearance</h3><label class="pr-field">Materials<select data-pr="material">${Object.entries(palettes).map(([k,p])=>`<option value="${k}" ${prefs.material===k?'selected':''}>${p.label}</option>`).join('')}</select></label><label class="pr-field">Daylight<select data-pr="light"><option value="overcast" ${prefs.light==='overcast'?'selected':''}>Soft daylight</option><option value="warm" ${prefs.light==='warm'?'selected':''}>Afternoon sun</option></select></label>${[['context','Neighbourhood'],['trees','Trees, people and cars'],['proposal','Show proposal']].map(([k,t])=>`<label class="pr-check"><input type="checkbox" data-pr="${k}" ${prefs[k]?'checked':''}> ${t}</label>`).join('')}<p class="ex-note">Hide the proposal to see the site context. Existing buildings on the selected site are not modelled.</p></section><section><h3>Vancouver context</h3><p class="ex-note">Street and lane gaps follow the bundled City parcels. Cottages, duplexes, walk-ups and laneway homes are illustrative typologies placed within estimated footprints. Google Earth 3D is not connected.</p></section><section><h3>Explore</h3><button data-pr-demo aria-pressed="false">Play orbit demo</button><p class="ex-note">Drag to orbit · scroll to zoom · right-drag to pan. Use the camera buttons to reset.</p><p class="ex-note">Lighting is illustrative daylight, not a solar study.</p></section>`;
 function bind(box){box.querySelectorAll('[data-pr-camera]').forEach(b=>b.onclick=()=>{prefs.camera=b.dataset.prCamera;setCamera();});box.querySelectorAll('[data-pr]').forEach(el=>el.onchange=()=>{prefs[el.dataset.pr]=el.type==='checkbox'?el.checked:el.value;if(['material','light'].includes(el.dataset.pr))render({stage,result:r,context:ctx,frame,states});else if(active){active.model.context.visible=prefs.context;active.model.trees.visible=prefs.context&&prefs.trees;active.model.proposal.visible=prefs.proposal;updateCaption();}});box.querySelector('[data-pr-demo]').onclick=()=>{if(!active)return;active.controls.autoRotate=!active.controls.autoRotate;syncDemo();};}
 const config={step:'presentation',states,site:ctx.addr,defaultView:'presentation',views:[{id:'presentation',label:'Rendering',node:panel}],figures:[['Design',ready?designName():'—'],['Storeys',r.o.floors],['Units',r.count||'—']],mode:(extra?.html||'')+mode,bindMode:box=>{bind(box);extra?.bind?.(box);},primary:root.EXPORT_STUDY?{...root.EXPORT_STUDY.action(),disabled:!ready}:{label:'Export image · PNG',disabled:!ready,onClick:exportImage},secondary:[{label:'Back to review',onClick:()=>root.APP.showTab('egress')}],status:'Presentation of the current schematic design · review findings remain applicable'};
 SH?.render(config);
 if(!SH?.isOn()){const controls=document.createElement('aside');controls.className='pr-sheet-controls';controls.innerHTML=mode+'<button data-pr-export>Export image · PNG</button>';stage.appendChild(controls);bind(controls);controls.querySelector('[data-pr-export]').onclick=exportImage;}
 if(!ready){host.innerHTML='<div class="pr-empty"><h2>Generate a unit layout first</h2><p>The presentation uses the same building as your reviewed plans.</p><button>Go to units</button></div>';host.querySelector('button').onclick=()=>root.APP.showTab('units');return;}
 try{
  const T=root.THREE,renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(root.devicePixelRatio||1,2));renderer.setClearColor(0xfafaf8);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputEncoding=T.sRGBEncoding;renderer.toneMapping=T.NoToneMapping;host.appendChild(renderer.domElement);
  const scene=new T.Scene(),camera=new T.PerspectiveCamera(42,1,.1,1000),controls=new T.OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.maxPolarAngle=Math.PI/2-.01;controls.minDistance=8;controls.maxDistance=230;controls.autoRotateSpeed=.7;
  // Drawing light: flat ambient fill and one sun for crisp, readable shadows; no sky, no fog, no reflections.
  const warm=prefs.light==='warm';scene.background=new T.Color(0xfafaf8);scene.add(new T.AmbientLight(0xffffff,warm?.62:.7));const sun=new T.DirectionalLight(warm?0xfff1dc:0xffffff,warm?.6:.45);sun.position.set(r.o.W/2-60,warm?55:70,-r.o.D/2+40);sun.shadow.radius=3;sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-90,right:90,top:90,bottom:-90,near:1,far:220});sun.shadow.bias=-.0003;sun.shadow.normalBias=.035;sun.target.position.set(r.o.W/2,0,-r.o.D/2);scene.add(sun,sun.target);
  const model=sceneModel(r,around);scene.add(model.group);active={renderer,scene,camera,controls,model,r,ctx,host,raf:null};
  const fit=()=>{if(!active||active.host!==host)return;const w=host.clientWidth,h=host.clientHeight;if(w&&h){renderer.setSize(w,h,false);active.camera.aspect=w/h;fitLens(active.camera,r);}};active.ro=new ResizeObserver(fit);active.ro.observe(host);fit();setCamera();
  controls.addEventListener('start',()=>{controls.autoRotate=false;syncDemo();panel.querySelector('.pr-camera').textContent='Custom view';});
  const loop=()=>{if(!active||active.host!==host)return;if(!host.isConnected){dispose();return;}active.raf=requestAnimationFrame(loop);if(document.hidden||host.clientWidth===0)return;controls.update();root.PRESENTATION_DRAWING.resolution(renderer);renderer.render(scene,active.camera);};loop();
  host.onkeydown=e=>{if(e.key==='Escape'){controls.autoRotate=false;syncDemo();}else if(e.key==='Home'){e.preventDefault();setCamera();}};
 }catch(error){dispose();host.innerHTML='<div class="pr-empty"><h2>3D rendering is unavailable</h2><p>Enable hardware acceleration in your browser, then reopen Presentation. Your design is unchanged.</p></div>';SH?.status('The 3D renderer could not start.');}
 function syncDemo(){document.querySelectorAll('[data-pr-demo]').forEach(b=>{const on=!!active?.controls.autoRotate;b.textContent=on?'Pause orbit demo':'Play orbit demo';b.setAttribute('aria-pressed',String(on));});}
 function updateCaption(){panel.querySelector('.pr-caption').textContent=(prefs.proposal?'Proposal shown. ':'Site context only; existing buildings on this site are not modelled. ')+(prefs.context&&around?.buildings?.length?'Neighbouring buildings approximate; trees, sidewalks and materials illustrative.':'Neighbourhood hidden or unavailable.');}
 function setCamera(){if(!active)return;const ortho=prefs.camera==='axon';if(ortho!==!!active.camera.isOrthographicCamera){const aspect=active.camera.aspect;active.camera=ortho?new root.THREE.OrthographicCamera(-1,1,1,-1,.1,1000):new root.THREE.PerspectiveCamera(42,aspect,.1,1000);active.camera.aspect=aspect;active.controls.object=active.camera;}const p=cameraPose(r,prefs.camera),v=q=>new root.THREE.Vector3(q[0],q[1],-q[2]);active.controls.autoRotate=false;active.camera.position.copy(v(p.position));active.controls.target.copy(v(p.target));active.controls.update();fitLens(active.camera,r);
  // eye-level cameras: a street tree right in front of the lens would hide the building, so it steps aside
  const clear=q=>ortho||prefs.camera==='corner'||q.position.distanceTo(active.camera.position)>16;active.model.trees.children.forEach(q=>{q.visible=clear(q);});active.model.context.children.forEach(q=>{if(['car','street-light','ground-shadow'].includes(q.userData.detail))q.visible=clear(q);});panel.querySelector('.pr-camera').textContent={axon:'Neighbourhood axon',hero:'Street corner',street:'Street view',corner:'Elevated corner',lane:'Lane view'}[prefs.camera];document.querySelectorAll('[data-pr-camera]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.prCamera===prefs.camera)));syncDemo();updateCaption();}
 exportShot=exportImage;function exportImage(){if(!active){SH?.status('Open a supported 3D view before exporting.');return;}const a=active,size=a.renderer.getSize(new root.THREE.Vector2()),ratio=a.renderer.getPixelRatio(),aspect=a.camera.aspect,fov=a.camera.fov,left=a.camera.left,right=a.camera.right;try{a.controls.autoRotate=false;syncDemo();a.renderer.setPixelRatio(1);a.renderer.setSize(3072,1728,false);a.camera.aspect=3072/1728;if(a.camera.isOrthographicCamera){const half=(a.camera.top-a.camera.bottom)/2;a.camera.left=-half*a.camera.aspect;a.camera.right=half*a.camera.aspect;}a.camera.updateProjectionMatrix();root.PRESENTATION_DRAWING.resolution(a.renderer);a.renderer.render(a.scene,a.camera);const canvas=document.createElement('canvas');canvas.width=3072;canvas.height=1848;const g=canvas.getContext('2d');g.fillStyle='#fff';g.fillRect(0,0,3072,1848);g.drawImage(a.renderer.domElement,0,0);g.fillStyle='#111417';g.font='28px Arial';g.fillText(`${ctx.addr||'R3 study'} · ${panel.querySelector('.pr-camera').textContent} · Design ${revision(r)}`,40,1770,2980);g.font='23px Arial';g.fillText(`${prefs.proposal?'Proposal':'Site context only'} · Neighbours approximate; landscaping, materials and daylight illustrative · ${new Date().toISOString().slice(0,10)}`,40,1815,2980);canvas.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`r3-presentation-${revision(r)}-${prefs.camera}.png`;link.click();setTimeout(()=>URL.revokeObjectURL(url),10000);},'image/png');}catch(e){SH?.status('Image export failed. Try reopening Presentation.');}finally{a.renderer.setPixelRatio(ratio);a.renderer.setSize(size.x,size.y,false);a.camera.aspect=aspect;a.camera.fov=fov;if(a.camera.isOrthographicCamera){a.camera.left=left;a.camera.right=right;}a.camera.updateProjectionMatrix();}}
}
root.addEventListener?.('r3-tab',e=>{if(e.detail!=='presentation')dispose();});
// the option's name for titles (the saved option, else the generated layout), never the internal revision hash
function designName(){return root.EXPORT_STUDY?.name?.(root.UNITS_UI?.study?.())||'Current design';}
root.PRESENTATION={exportImage:()=>exportShot?.(),canExport:()=>!!active,render,dispose,sceneModel,cameraPose,fitLens,revision,palettes};
})(typeof window!=='undefined'?window:globalThis);
